/**
 * DeutschMeister A1 — Modul 3: Vollständiger Goethe A1 Wortschatz (770+ Wörter)
 * Lückenlose Wortliste nach dem offiziellen Goethe-Zertifikat A1 Referenzrahmen.
 */

const rawA1Vocab = [
  // =========================================================================
  // 1. ALLTAG, BEGRÜSSUNG & BASISDATEN (Personal Info, Forms & Basics)
  // =========================================================================
  ['der Name', 'name', 'alltag', 'der', 'Namen'],
  ['der Vorname', 'first name', 'alltag', 'der', 'Vornamen'],
  ['der Nachname', 'last name / surname', 'alltag', 'der', 'Nachnamen'],
  ['die Adresse', 'address', 'alltag', 'die', 'Adressen'],
  ['die Straße', 'street', 'alltag', 'die', 'Straßen'],
  ['die Hausnummer', 'house number', 'alltag', 'die', 'Hausnummern'],
  ['die Postleitzahl', 'postal code', 'alltag', 'die', 'Postleitzahlen'],
  ['der Wohnort', 'place of residence', 'alltag', 'der', 'Wohnorte'],
  ['die Stadt', 'city / town', 'alltag', 'die', 'Städte'],
  ['das Land', 'country / countryside', 'alltag', 'das', 'Länder'],
  ['die Herkunft', 'origin', 'alltag', 'die', 'Herkünfte'],
  ['die Sprache', 'language', 'alltag', 'die', 'Sprachen'],
  ['die Muttersprache', 'native language', 'alltag', 'die', 'Muttersprachen'],
  ['die Fremdsprache', 'foreign language', 'alltag', 'die', 'Fremdsprachen'],
  ['das Geburtsdatum', 'date of birth', 'alltag', 'das', 'Geburtsdaten'],
  ['der Geburtsort', 'place of birth', 'alltag', 'der', 'Geburtsorte'],
  ['das Geburtsjahr', 'year of birth', 'alltag', 'das', 'Geburtsjahre'],
  ['das Alter', 'age', 'alltag', 'das', '-'],
  ['der Familienstand', 'marital status', 'alltag', 'der', '-'],
  ['die Staatsangehörigkeit', 'citizenship / nationality', 'alltag', 'die', 'Staatsangehörigkeiten'],
  ['das Formular', 'official form', 'alltag', 'das', 'Formulare'],
  ['die Anmeldung', 'registration', 'alltag', 'die', 'Anmeldungen'],
  ['die Abmeldung', 'deregistration', 'alltag', 'die', 'Abmeldungen'],
  ['die Bestätigung', 'confirmation', 'alltag', 'die', 'Bestätigungen'],
  ['die Unterschrift', 'signature', 'alltag', 'die', 'Unterschriften'],
  ['der Ausweis', 'ID card', 'alltag', 'der', 'Ausweise'],
  ['der Personalausweis', 'identity card', 'alltag', 'der', 'Personalausweise'],
  ['der Reisepass', 'passport', 'alltag', 'der', 'Reisepässe'],
  ['das Visum', 'visa', 'alltag', 'das', 'Visa'],
  ['die Telefonnummer', 'telephone number', 'alltag', 'die', 'Telefonnummern'],
  ['die Handynummer', 'mobile phone number', 'alltag', 'die', 'Handynummern'],
  ['die Vorwahl', 'area code', 'alltag', 'die', 'Vorwahlen'],
  ['die E-Mail-Adresse', 'email address', 'alltag', 'die', 'E-Mail-Adressen'],
  ['der Herr', 'mister / gentleman', 'alltag', 'der', 'Herren'],
  ['die Frau', 'woman / Mrs. / wife', 'alltag', 'die', 'Frauen'],
  ['die Dame', 'lady', 'alltag', 'die', 'Damen'],
  ['das Fräulein', 'miss (dated)', 'alltag', 'das', 'Fräulein'],
  ['das Beispiel', 'example', 'alltag', 'das', 'Beispiele'],
  ['das Wort', 'word', 'alltag', 'das', 'Wörter'],
  ['der Satz', 'sentence', 'alltag', 'der', 'Sätze'],
  ['die Frage', 'question', 'alltag', 'die', 'Fragen'],
  ['die Antwort', 'answer / reply', 'alltag', 'die', 'Antworten'],
  ['der Buchstabe', 'letter (alphabet)', 'alltag', 'der', 'Buchstaben'],
  ['das Alphabet', 'alphabet', 'alltag', 'das', 'Alphabete'],
  ['die Nummer', 'number', 'alltag', 'die', 'Nummern'],
  ['die Zahl', 'digit / figure', 'alltag', 'die', 'Zahlen'],
  ['der Zettel', 'slip of paper / note', 'alltag', 'der', 'Zettel'],
  ['der Gruß', 'greeting', 'alltag', 'der', 'Grüße'],
  ['der Dank', 'gratitude / thanks', 'alltag', 'der', '-'],
  ['die Entschuldigung', 'apology / excuse', 'alltag', 'die', 'Entschuldigungen'],
  ['die Bitte', 'request / plea', 'alltag', 'die', 'Bitten'],
  ['das Problem', 'problem', 'alltag', 'das', 'Probleme'],
  ['die Hilfe', 'help / assistance', 'alltag', 'die', '-'],
  ['die Information', 'information', 'alltag', 'die', 'Informationen'],
  ['die Auskunft', 'information desk', 'alltag', 'die', 'Auskünfte'],
  ['der Anfang', 'beginning / start', 'alltag', 'der', 'Anfänge'],
  ['das Ende', 'end', 'alltag', 'das', 'Enden'],
  ['der Grund', 'reason / ground', 'alltag', 'der', 'Gründe'],
  ['der Fehler', 'mistake / error', 'alltag', 'der', 'Fehler'],
  ['das Ding / die Sache', 'thing / item', 'alltag', 'das', 'Dinge / Sachen'],

  // =========================================================================
  // 2. FAMILIE, BEZIEHUNGEN & MENSCHEN (Family & People)
  // =========================================================================
  ['die Familie', 'family', 'familie', 'die', 'Familien'],
  ['die Eltern', 'parents', 'familie', 'die', 'Eltern'],
  ['der Vater', 'father', 'familie', 'der', 'Väter'],
  ['die Mutter', 'mother', 'familie', 'die', 'Mütter'],
  ['der Papa', 'dad', 'familie', 'der', 'Papas'],
  ['die Mama', 'mom', 'familie', 'die', 'Mamas'],
  ['der Sohn', 'son', 'familie', 'der', 'Söhne'],
  ['die Tochter', 'daughter', 'familie', 'die', 'Töchter'],
  ['das Kind', 'child', 'familie', 'das', 'Kinder'],
  ['der Bruder', 'brother', 'familie', 'der', 'Brüder'],
  ['die Schwester', 'sister', 'familie', 'die', 'Schwestern'],
  ['die Geschwister', 'siblings', 'familie', 'die', 'Geschwister'],
  ['die Großeltern', 'grandparents', 'familie', 'die', 'Großeltern'],
  ['der Großvater / Opa', 'grandfather', 'familie', 'der', 'Großväter / Opas'],
  ['die Großmutter / Oma', 'grandmother', 'familie', 'die', 'Großmütter / Omas'],
  ['das Enkelkind', 'grandchild', 'familie', 'das', 'Enkelkinder'],
  ['der Enkel', 'grandson', 'familie', 'der', 'Enkel'],
  ['die Enkelin', 'granddaughter', 'familie', 'die', 'Enkelinnen'],
  ['der Onkel', 'uncle', 'familie', 'der', 'Onkel'],
  ['die Tante', 'aunt', 'familie', 'die', 'Tanten'],
  ['der Neffe', 'nephew', 'familie', 'der', 'Neffen'],
  ['die Nichte', 'niece', 'familie', 'die', 'Nichten'],
  ['der Cousin', 'male cousin', 'familie', 'der', 'Cousins'],
  ['die Cousine', 'female cousin', 'familie', 'die', 'Cousinen'],
  ['der Mann', 'man / husband', 'familie', 'der', 'Männer'],
  ['die Ehefrau', 'wife', 'familie', 'die', 'Ehefrauen'],
  ['der Ehemann', 'husband', 'familie', 'der', 'Ehemänner'],
  ['das Ehepaar', 'married couple', 'familie', 'das', 'Ehepaare'],
  ['der Partner', 'partner (male)', 'familie', 'der', 'Partner'],
  ['die Partnerin', 'partner (female)', 'familie', 'die', 'Partnerinnen'],
  ['der Freund', 'friend / boyfriend', 'familie', 'der', 'Freunde'],
  ['die Freundin', 'friend / girlfriend', 'familie', 'die', 'Freundinnen'],
  ['der Kollege', 'colleague (male)', 'familie', 'der', 'Kollegen'],
  ['die Kollegin', 'colleague (female)', 'familie', 'die', 'Kolleginnen'],
  ['der Nachbar', 'neighbor (male)', 'familie', 'der', 'Nachbarn'],
  ['die Nachbarin', 'neighbor (female)', 'familie', 'die', 'Nachbarinnen'],
  ['der Gast', 'guest', 'familie', 'der', 'Gäste'],
  ['die Leute', 'people', 'familie', 'die', 'Leute'],
  ['der Mensch', 'human being / person', 'familie', 'der', 'Menschen'],
  ['das Baby', 'baby', 'familie', 'das', 'Babys'],
  ['der Junge', 'boy', 'familie', 'der', 'Jungen'],
  ['das Mädchen', 'girl', 'familie', 'das', 'Mädchen'],
  ['der Jugendliche', 'youth / teenager', 'familie', 'der', 'Jugendlichen'],
  ['der Erwachsene', 'adult', 'familie', 'der', 'Erwachsenen'],

  // =========================================================================
  // 3. ESSEN, TRINKEN & GASTRONOMIE (Food, Drinks, Groceries & Kitchen)
  // =========================================================================
  ['das Essen', 'food / meal', 'essen', 'das', '-'],
  ['das Lebensmittel', 'groceries / foodstuff', 'essen', 'das', 'Lebensmittel'],
  ['das Getränk', 'drink / beverage', 'essen', 'das', 'Getränke'],
  ['das Frühstück', 'breakfast', 'essen', 'das', 'Frühstücke'],
  ['das Mittagessen', 'lunch', 'essen', 'das', 'Mittagessen'],
  ['das Abendessen', 'dinner / supper', 'essen', 'das', 'Abendessen'],
  ['das Brot', 'bread', 'essen', 'das', 'Brote'],
  ['das Brötchen / die Semmel', 'bread roll', 'essen', 'das', 'Brötchen'],
  ['das Vollkornbrot', 'whole grain bread', 'essen', 'das', 'Vollkornbrote'],
  ['das Toastbrot', 'toast bread', 'essen', 'das', 'Toastbrote'],
  ['die Butter', 'butter', 'essen', 'die', '-'],
  ['die Margarine', 'margarine', 'essen', 'die', '-'],
  ['der Käse', 'cheese', 'essen', 'der', 'Käse'],
  ['die Wurst', 'sausage / cold cuts', 'essen', 'die', 'Würste'],
  ['der Schinken', 'ham', 'essen', 'der', 'Schinken'],
  ['das Fleisch', 'meat', 'essen', 'das', '-'],
  ['das Rindfleisch', 'beef', 'essen', 'das', '-'],
  ['das Schweinefleisch', 'pork', 'essen', 'das', '-'],
  ['das Hähnchen / Huhn', 'chicken', 'essen', 'das', 'Hähnchen'],
  ['das Schnitzel', 'cutlet / schnitzel', 'essen', 'das', 'Schnitzel'],
  ['die Bratwurst', 'fried sausage', 'essen', 'die', 'Bratwürste'],
  ['der Fisch', 'fish', 'essen', 'der', 'Fische'],
  ['der Lachs', 'salmon', 'essen', 'der', 'Lachse'],
  ['das Ei', 'egg', 'essen', 'das', 'Eier'],
  ['die Milch', 'milk', 'essen', 'die', '-'],
  ['der Joghurt', 'yogurt', 'essen', 'der', 'Joghurts'],
  ['der Quark', 'quark / curd', 'essen', 'der', '-'],
  ['die Sahne', 'cream', 'essen', 'die', '-'],
  ['das Obst', 'fruit', 'essen', 'das', '-'],
  ['das Gemüse', 'vegetables', 'essen', 'das', '-'],
  ['der Apfel', 'apple', 'essen', 'der', 'Äpfel'],
  ['die Birne', 'pear', 'essen', 'die', 'Birnen'],
  ['die Banane', 'banana', 'essen', 'die', 'Bananen'],
  ['die Orange / Apfelsine', 'orange', 'essen', 'die', 'Orangen'],
  ['die Zitrone', 'lemon', 'essen', 'die', 'Zitronen'],
  ['die Erdbeere', 'strawberry', 'essen', 'die', 'Erdbeeren'],
  ['die Traube / Weintraube', 'grape', 'essen', 'die', 'Trauben'],
  ['die Kirsche', 'cherry', 'essen', 'die', 'Kirschen'],
  ['die Tomate', 'tomato', 'essen', 'die', 'Tomaten'],
  ['die Gurke', 'cucumber', 'essen', 'die', 'Gurken'],
  ['die Kartoffel', 'potato', 'essen', 'die', 'Kartoffeln'],
  ['die Pommes frites', 'french fries', 'essen', 'die', 'Pommes frites'],
  ['die Zwiebel', 'onion', 'essen', 'die', 'Zwiebeln'],
  ['der Knoblauch', 'garlic', 'essen', 'der', '-'],
  ['der Salat', 'salad / lettuce', 'essen', 'der', 'Salate'],
  ['die Karotte / Möhre', 'carrot', 'essen', 'die', 'Karotten'],
  ['der Pilz', 'mushroom', 'essen', 'der', 'Pilze'],
  ['der Reis', 'rice', 'essen', 'der', '-'],
  ['die Nudeln / Pasta', 'noodles / pasta', 'essen', 'die', 'Nudeln'],
  ['die Spaghetti', 'spaghetti', 'essen', 'die', 'Spaghetti'],
  ['die Pizza', 'pizza', 'essen', 'die', 'Pizzen'],
  ['die Suppe', 'soup', 'essen', 'die', 'Suppen'],
  ['das Salz', 'salt', 'essen', 'das', '-'],
  ['der Pfeffer', 'pepper', 'essen', 'der', '-'],
  ['der Zucker', 'sugar', 'essen', 'der', '-'],
  ['das Öl', 'oil', 'essen', 'das', 'Öle'],
  ['der Essig', 'vinegar', 'essen', 'der', 'Essige'],
  ['der Senf', 'mustard', 'essen', 'der', '-'],
  ['die Mayonnaise', 'mayonnaise', 'essen', 'die', '-'],
  ['die Marmelade', 'jam / marmalade', 'essen', 'die', 'Marmeladen'],
  ['der Honig', 'honey', 'essen', 'der', '-'],
  ['das Müsli', 'muesli / cereal', 'essen', 'das', 'Müslis'],
  ['das Wasser', 'water', 'essen', 'das', '-'],
  ['das Mineralwasser', 'mineral water', 'essen', 'das', '-'],
  ['das Leitungswasser', 'tap water', 'essen', 'das', '-'],
  ['der Kaffee', 'coffee', 'essen', 'der', 'Kaffees'],
  ['der Espresso', 'espresso', 'essen', 'der', 'Espressos'],
  ['der Cappuccino', 'cappuccino', 'essen', 'der', 'Cappuccinos'],
  ['der Tee', 'tea', 'essen', 'der', 'Tees'],
  ['der Saft', 'juice', 'essen', 'der', 'Säfte'],
  ['der Apfelsaft', 'apple juice', 'essen', 'der', 'Apfelsäfte'],
  ['die Apfelschorle', 'apple spritzer', 'essen', 'die', 'Apfelschorlen'],
  ['der Orangensaft', 'orange juice', 'essen', 'der', 'Orangensäfte'],
  ['die Cola', 'coke / cola', 'essen', 'die', 'Colas'],
  ['die Limonade', 'lemonade', 'essen', 'die', 'Limonaden'],
  ['das Bier', 'beer', 'essen', 'das', 'Biere'],
  ['der Wein', 'wine', 'essen', 'der', 'Weine'],
  ['der Rotwein', 'red wine', 'essen', 'der', 'Rotweine'],
  ['der Weißwein', 'white wine', 'essen', 'der', 'Weißweine'],
  ['der Kuchen', 'cake', 'essen', 'der', 'Kuchen'],
  ['die Torte', 'layer cake / tart', 'essen', 'die', 'Torten'],
  ['der Keks', 'biscuit / cookie', 'essen', 'der', 'Kekse'],
  ['die Schokolade', 'chocolate', 'essen', 'die', 'Schokoladen'],
  ['das Eis', 'ice cream', 'essen', 'das', '-'],
  ['das Bonbon', 'candy / sweet', 'essen', 'das', 'Bonbons'],
  ['das Restaurant', 'restaurant', 'essen', 'das', 'Restaurants'],
  ['die Gaststätte / Kneipe', 'pub / tavern', 'essen', 'die', 'Gaststätten'],
  ['das Café', 'café', 'essen', 'das', 'Cafés'],
  ['die Bäckerei', 'bakery', 'essen', 'die', 'Bäckereien'],
  ['die Metzgerei / Fleischerei', 'butcher shop', 'essen', 'die', 'Metzgereien'],
  ['der Supermarkt', 'supermarket', 'essen', 'der', 'Supermärkte'],
  ['der Markt', 'market', 'essen', 'der', 'Märkte'],
  ['der Kiosk', 'kiosk / newsstand', 'essen', 'der', 'Kioske'],
  ['die Mensa', 'university cafeteria', 'essen', 'die', 'Mensen'],
  ['die Kantine', 'office cafeteria', 'essen', 'die', 'Kantinen'],
  ['die Speisekarte', 'menu', 'essen', 'die', 'Speisekarten'],
  ['die Rechnung', 'bill / receipt', 'essen', 'die', 'Rechnungen'],
  ['das Trinkgeld', 'tip', 'essen', 'das', '-'],
  ['der Kellner', 'waiter', 'essen', 'der', 'Kellner'],
  ['die Kellnerin', 'waitress', 'essen', 'die', 'Kellnerinnen'],
  ['der Koch', 'cook / chef (male)', 'essen', 'der', 'Köche'],
  ['die Köchin', 'cook / chef (female)', 'essen', 'die', 'Köchinnen'],
  ['die Flasche', 'bottle', 'essen', 'die', 'Flaschen'],
  ['das Glas', 'glass / jar', 'essen', 'das', 'Gläser'],
  ['die Tasse', 'cup / mug', 'essen', 'die', 'Tassen'],
  ['der Teller', 'plate', 'essen', 'der', 'Teller'],
  ['die Schüssel', 'bowl', 'essen', 'die', 'Schüsseln'],
  ['die Gabel', 'fork', 'essen', 'die', 'Gabeln'],
  ['das Messer', 'knife', 'essen', 'das', 'Messer'],
  ['der Löffel', 'spoon', 'essen', 'der', 'Löffel'],
  ['die Dose', 'can / tin', 'essen', 'die', 'Dosen'],
  ['die Packung', 'packet / box', 'essen', 'die', 'Packungen'],
  ['die Tüte', 'bag (plastic/paper)', 'essen', 'die', 'Tüten'],
  ['das Stück', 'piece', 'essen', 'das', 'Stücke'],
  ['das Kilo / Kilogramm', 'kilogram', 'essen', 'das', 'Kilos'],
  ['das Pfund', 'pound (500g)', 'essen', 'das', 'Pfund'],
  ['das Gramm', 'gram', 'essen', 'das', 'Gramm'],
  ['der Liter', 'liter', 'essen', 'der', 'Liter'],
  ['der Preis', 'price', 'essen', 'der', 'Preise'],
  ['der Euro', 'euro', 'essen', 'der', 'Euro'],
  ['der Cent', 'cent', 'essen', 'der', 'Cent'],
  ['der Hunger', 'hunger', 'essen', 'der', '-'],
  ['der Durst', 'thirst', 'essen', 'der', '-'],

  // =========================================================================
  // 4. WOHNEN, HAUSHALT & GEBÄUDE (Housing, Furniture & Household)
  // =========================================================================
  ['die Wohnung', 'apartment / flat', 'wohnen', 'die', 'Wohnungen'],
  ['das Haus', 'house', 'wohnen', 'das', 'Häuser'],
  ['das Apartment', 'studio apartment', 'wohnen', 'das', 'Apartments'],
  ['das Zimmer', 'room', 'wohnen', 'das', 'Zimmer'],
  ['das Wohnzimmer', 'living room', 'wohnen', 'das', 'Wohnzimmer'],
  ['das Schlafzimmer', 'bedroom', 'wohnen', 'das', 'Schlafzimmer'],
  ['die Küche', 'kitchen', 'wohnen', 'die', 'Küchen'],
  ['das Bad / Badezimmer', 'bathroom', 'wohnen', 'das', 'Bäder'],
  ['die Toilette / das WC', 'toilet / restroom', 'wohnen', 'die', 'Toiletten'],
  ['der Flur / der Korridor', 'hallway / corridor', 'wohnen', 'der', 'Flure'],
  ['der Balkon', 'balcony', 'wohnen', 'der', 'Balkone'],
  ['die Terrasse', 'terrace / patio', 'wohnen', 'die', 'Terrassen'],
  ['der Garten', 'garden / yard', 'wohnen', 'der', 'Gärten'],
  ['der Keller', 'cellar / basement', 'wohnen', 'der', 'Keller'],
  ['das Dach', 'roof', 'wohnen', 'das', 'Dächer'],
  ['die Garage', 'garage', 'wohnen', 'die', 'Garagen'],
  ['der Parkplatz', 'parking space', 'wohnen', 'der', 'Parkplätze'],
  ['der Hof', 'courtyard', 'wohnen', 'der', 'Höfe'],
  ['die Treppe', 'stairs / staircase', 'wohnen', 'die', 'Treppen'],
  ['das Treppenhaus', 'stairwell', 'wohnen', 'das', 'Treppenhäuser'],
  ['der Aufzug / Fahrstuhl', 'elevator / lift', 'wohnen', 'der', 'Aufzüge'],
  ['der Stock / das Stockwerk', 'floor / story', 'wohnen', 'der', 'Stockwerke'],
  ['die Etage', 'floor / level', 'wohnen', 'die', 'Etagen'],
  ['das Erdgeschoss', 'ground floor', 'wohnen', 'das', '-'],
  ['der Eingang', 'entrance', 'wohnen', 'der', 'Eingänge'],
  ['der Ausgang', 'exit', 'wohnen', 'der', 'Ausgänge'],
  ['der Notausgang', 'emergency exit', 'wohnen', 'der', 'Notausgänge'],
  ['die Wand', 'wall', 'wohnen', 'die', 'Wände'],
  ['das Fenster', 'window', 'wohnen', 'das', 'Fenster'],
  ['die Tür', 'door', 'wohnen', 'die', 'Türen'],
  ['die Haustür', 'front door', 'wohnen', 'die', 'Haustüren'],
  ['der Schlüssel', 'key', 'wohnen', 'der', 'Schlüssel'],
  ['das Schloss', 'lock / palace', 'wohnen', 'das', 'Schlösser'],
  ['die Klingel', 'doorbell', 'wohnen', 'die', 'Klingeln'],
  ['der Briefkasten', 'mailbox', 'wohnen', 'der', 'Briefkästen'],
  ['die Miete', 'rent', 'wohnen', 'die', 'Mieten'],
  ['die Kaltmiete', 'base rent (cold)', 'wohnen', 'die', 'Kaltmieten'],
  ['die Warmmiete', 'total rent (warm)', 'wohnen', 'die', 'Warmmieten'],
  ['die Nebenkosten', 'utilities / additional fees', 'wohnen', 'die', 'Nebenkosten'],
  ['die Kaution', 'deposit', 'wohnen', 'die', 'Kautionen'],
  ['der Vermieter', 'landlord', 'wohnen', 'der', 'Vermieter'],
  ['die Vermieterin', 'landlady', 'wohnen', 'die', 'Vermieterinnen'],
  ['der Mieter', 'tenant (male)', 'wohnen', 'der', 'Mieter'],
  ['die Mieterin', 'tenant (female)', 'wohnen', 'die', 'Mieterinnen'],
  ['der Mietvertrag', 'lease / rental contract', 'wohnen', 'der', 'Mietverträge'],
  ['die Hausordnung', 'house rules', 'wohnen', 'die', 'Hausordnungen'],
  ['die Ruhezeit', 'quiet hours', 'wohnen', 'die', 'Ruhezeiten'],
  ['der Nachbar', 'neighbor', 'wohnen', 'der', 'Nachbarn'],
  ['der Umzug', 'relocation / move', 'wohnen', 'der', 'Umzüge'],
  ['das Möbel / die Möbel', 'furniture', 'wohnen', 'das', 'Möbel'],
  ['der Tisch', 'table', 'wohnen', 'der', 'Tische'],
  ['der Schreibtisch', 'desk', 'wohnen', 'der', 'Schreibtische'],
  ['der Esstisch', 'dining table', 'wohnen', 'der', 'Esstische'],
  ['der Stuhl', 'chair', 'wohnen', 'der', 'Stühle'],
  ['der Sessel', 'armchair', 'wohnen', 'der', 'Sessel'],
  ['das Sofa / die Couch', 'sofa / couch', 'wohnen', 'das', 'Sofas'],
  ['das Bett', 'bed', 'wohnen', 'das', 'Betten'],
  ['der Schrank', 'wardrobe / cupboard', 'wohnen', 'der', 'Schränke'],
  ['der Kleiderschrank', 'clothes wardrobe', 'wohnen', 'der', 'Kleiderschränke'],
  ['das Regal', 'shelf / bookcase', 'wohnen', 'das', 'Regale'],
  ['die Lampe', 'lamp / light', 'wohnen', 'die', 'Lampen'],
  ['das Licht', 'light', 'wohnen', 'das', 'Lichter'],
  ['der Spiegel', 'mirror', 'wohnen', 'der', 'Spiegel'],
  ['der Teppich', 'carpet / rug', 'wohnen', 'der', 'Teppiche'],
  ['das Bild', 'picture / painting', 'wohnen', 'das', 'Bilder'],
  ['die Uhr', 'clock / watch', 'wohnen', 'die', 'Uhren'],
  ['der Wecker', 'alarm clock', 'wohnen', 'der', 'Wecker'],
  ['die Heizung', 'heating / radiator', 'wohnen', 'die', 'Heizungen'],
  ['der Herd', 'stove / cooker', 'wohnen', 'der', 'Herde'],
  ['der Backofen', 'baking oven', 'wohnen', 'der', 'Backöfen'],
  ['der Kühlschrank', 'refrigerator', 'wohnen', 'der', 'Kühlschränke'],
  ['die Spülmaschine', 'dishwasher', 'wohnen', 'die', 'Spülmaschinen'],
  ['die Waschmaschine', 'washing machine', 'wohnen', 'die', 'Waschmaschinen'],
  ['das Waschbecken', 'sink / washbasin', 'wohnen', 'das', 'Waschbecken'],
  ['die Dusche', 'shower', 'wohnen', 'die', 'Duschen'],
  ['die Badewanne', 'bathtub', 'wohnen', 'die', 'Badewannen'],
  ['das Handtuch', 'towel', 'wohnen', 'das', 'Handtücher'],
  ['die Seife', 'soap', 'wohnen', 'die', 'Seifen'],
  ['das Shampoo', 'shampoo', 'wohnen', 'das', 'Shampoos'],
  ['die Zahnbürste', 'toothbrush', 'wohnen', 'die', 'Zahnbürsten'],
  ['die Zahnpasta', 'toothpaste', 'wohnen', 'die', 'Zahnpastas'],
  ['das Klopapier / Toilettenpapier', 'toilet paper', 'wohnen', 'das', '-'],
  ['der Müll / Abfall', 'trash / garbage', 'wohnen', 'der', '-'],
  ['der Mülleimer', 'trash can / bin', 'wohnen', 'der', 'Mülleimer'],
  ['der Strom', 'electricity / power', 'wohnen', 'der', '-'],
  ['das Wasser', 'water', 'wohnen', 'das', '-'],
  ['das Gas', 'gas', 'wohnen', 'das', '-'],

  // =========================================================================
  // 5. BERUF, ARBEIT & BILDUNG (Jobs, Work, Office & School)
  // =========================================================================
  ['der Beruf', 'profession / occupation', 'beruf', 'der', 'Berufe'],
  ['die Arbeit', 'work / job', 'beruf', 'die', 'Arbeiten'],
  ['der Job', 'job', 'beruf', 'der', 'Jobs'],
  ['der Arbeitsplatz', 'workplace', 'beruf', 'der', 'Arbeitsplätze'],
  ['die Stelle', 'position / job opening', 'beruf', 'die', 'Stellen'],
  ['die Stellenanzeige', 'job advertisement', 'beruf', 'die', 'Stellenanzeigen'],
  ['die Bewerbung', 'job application', 'beruf', 'die', 'Bewerbungen'],
  ['der Lebenslauf', 'curriculum vitae / resume', 'beruf', 'der', 'Lebensläufe'],
  ['das Zeugnis', 'certificate / report card', 'beruf', 'das', 'Zeugnisse'],
  ['der Vertrag', 'contract', 'beruf', 'der', 'Verträge'],
  ['der Arbeitsvertrag', 'employment contract', 'beruf', 'der', 'Arbeitsverträge'],
  ['die Kündigung', 'termination / notice', 'beruf', 'die', 'Kündigungen'],
  ['das Gehalt / der Lohn', 'salary / wage', 'beruf', 'das', 'Gehälter / Löhne'],
  ['das Geld', 'money', 'beruf', 'das', '-'],
  ['die Firma / das Unternehmen', 'company / firm', 'beruf', 'die', 'Firmen'],
  ['der Betrieb', 'enterprise / factory', 'beruf', 'der', 'Betriebe'],
  ['das Büro', 'office', 'beruf', 'das', 'Büros'],
  ['die Fabrik', 'factory', 'beruf', 'die', 'Fabriken'],
  ['die Werkstatt', 'workshop / repair shop', 'beruf', 'die', 'Werkstätten'],
  ['der Chef', 'boss (male)', 'beruf', 'der', 'Chefs'],
  ['die Chefin', 'boss (female)', 'beruf', 'die', 'Chefinnen'],
  ['der Leiter / Direktor', 'director / head', 'beruf', 'der', 'Leiter'],
  ['der Mitarbeiter', 'employee / coworker', 'beruf', 'der', 'Mitarbeiter'],
  ['die Mitarbeiterin', 'employee (female)', 'beruf', 'die', 'Mitarbeiterinnen'],
  ['der Kollege', 'colleague (male)', 'beruf', 'der', 'Kollegen'],
  ['die Kollegin', 'colleague (female)', 'beruf', 'die', 'Kolleginnen'],
  ['der Kunde', 'client / customer (male)', 'beruf', 'der', 'Kunden'],
  ['die Kundin', 'client / customer (female)', 'beruf', 'die', 'Kundinnen'],
  ['der Arzt', 'physician / doctor (male)', 'beruf', 'der', 'Ärzte'],
  ['die Ärztin', 'physician / doctor (female)', 'beruf', 'die', 'Ärztinnen'],
  ['der Zahnarzt', 'dentist (male)', 'beruf', 'der', 'Zahnärzte'],
  ['die Zahnärztin', 'dentist (female)', 'beruf', 'die', 'Zahnärztinnen'],
  ['der Krankenpfleger', 'nurse (male)', 'beruf', 'der', 'Krankenpfleger'],
  ['die Krankenschwester', 'nurse (female)', 'beruf', 'die', 'Krankenschwestern'],
  ['der Lehrer', 'teacher (male)', 'beruf', 'der', 'Lehrer'],
  ['die Lehrerin', 'teacher (female)', 'beruf', 'die', 'Lehrerinnen'],
  ['der Schüler', 'school pupil (male)', 'beruf', 'der', 'Schüler'],
  ['die Schülerin', 'school pupil (female)', 'beruf', 'die', 'Schülerinnen'],
  ['der Student', 'university student (male)', 'beruf', 'der', 'Studenten'],
  ['die Studentin', 'university student (female)', 'beruf', 'die', 'Studentinnen'],
  ['der Professor', 'professor (male)', 'beruf', 'der', 'Professoren'],
  ['die Professorin', 'professor (female)', 'beruf', 'die', 'Professorinnen'],
  ['der Ingenieur', 'engineer (male)', 'beruf', 'der', 'Ingenieure'],
  ['die Ingenieurin', 'engineer (female)', 'beruf', 'die', 'Ingenieurinnen'],
  ['der Informatiker', 'computer scientist / IT specialist', 'beruf', 'der', 'Informatiker'],
  ['der Architekt', 'architect (male)', 'beruf', 'der', 'Architekten'],
  ['der Verkäufer', 'shop assistant (male)', 'beruf', 'der', 'Verkäufer'],
  ['die Verkäuferin', 'shop assistant (female)', 'beruf', 'die', 'Verkäuferinnen'],
  ['der Kaufmann', 'businessman / merchant', 'beruf', 'der', 'Kaufleute'],
  ['die Kauffrau', 'businesswoman', 'beruf', 'die', 'Kauffrauen'],
  ['der Handwerker', 'craftsman / tradesman', 'beruf', 'der', 'Handwerker'],
  ['der Mechaniker', 'mechanic', 'beruf', 'der', 'Mechaniker'],
  ['der Mechatroniker', 'automotive mechatronics tech', 'beruf', 'der', 'Mechatroniker'],
  ['der Elektriker', 'electrician', 'beruf', 'der', 'Elektriker'],
  ['der Maler', 'painter', 'beruf', 'der', 'Maler'],
  ['der Friseur', 'hairdresser (male)', 'beruf', 'der', 'Friseure'],
  ['die Friseurin', 'hairdresser (female)', 'beruf', 'die', 'Friseurinnen'],
  ['der Polizist', 'police officer (male)', 'beruf', 'der', 'Polizisten'],
  ['die Polizistin', 'police officer (female)', 'beruf', 'die', 'Polizistinnen'],
  ['der Fahrer', 'driver', 'beruf', 'der', 'Fahrer'],
  ['der Taxifahrer', 'taxi driver', 'beruf', 'der', 'Taxifahrer'],
  ['der Busfahrer', 'bus driver', 'beruf', 'der', 'Busfahrer'],
  ['die Hausfrau', 'homemaker / housewife', 'beruf', 'die', 'Hausfrauen'],
  ['der Rentner', 'pensioner / retiree', 'beruf', 'der', 'Rentner'],
  ['die Schule', 'school', 'beruf', 'die', 'Schulen'],
  ['die Grundschule', 'elementary school', 'beruf', 'die', 'Grundschulen'],
  ['die Universität / die Uni', 'university', 'beruf', 'die', 'Universitäten'],
  ['die Hochschule', 'college / university of applied sci', 'beruf', 'die', 'Hochschulen'],
  ['der Kurs', 'course / class', 'beruf', 'der', 'Kurse'],
  ['der Deutschkurs', 'German language course', 'beruf', 'der', 'Deutschkurse'],
  ['der Sprachkurs', 'language course', 'beruf', 'der', 'Sprachkurse'],
  ['der Unterricht', 'instruction / lessons', 'beruf', 'der', '-'],
  ['die Stunde / Unterrichtsstunde', 'lesson / class hour', 'beruf', 'die', 'Stunden'],
  ['die Pause', 'break / recess', 'beruf', 'die', 'Pausen'],
  ['die Mittagspause', 'lunch break', 'beruf', 'die', 'Mittagspausen'],
  ['die Hausaufgabe', 'homework', 'beruf', 'die', 'Hausaufgaben'],
  ['die Prüfung', 'exam / test', 'beruf', 'die', 'Prüfungen'],
  ['der Test', 'test', 'beruf', 'der', 'Tests'],
  ['das Zertifikat', 'certificate', 'beruf', 'das', 'Zertifikate'],
  ['die Note', 'grade / mark', 'beruf', 'die', 'Noten'],
  ['das Buch', 'book', 'beruf', 'das', 'Bücher'],
  ['das Lehrbuch / Kursbuch', 'textbook / coursebook', 'beruf', 'das', 'Lehrbücher'],
  ['das Arbeitsbuch', 'workbook', 'beruf', 'das', 'Arbeitsbücher'],
  ['das Wörterbuch', 'dictionary', 'beruf', 'das', 'Wörterbücher'],
  ['das Heft', 'notebook / exercise book', 'beruf', 'das', 'Hefte'],
  ['das Papier', 'paper', 'beruf', 'das', 'Papiere'],
  ['das Blatt', 'sheet (of paper)', 'beruf', 'das', 'Blätter'],
  ['der Stift', 'pen / pencil', 'beruf', 'der', 'Stifte'],
  ['der Kugelschreiber / Kuli', 'ballpoint pen', 'beruf', 'der', 'Kugelschreiber'],
  ['der Bleistift', 'pencil', 'beruf', 'der', 'Bleistifte'],
  ['der Textmarker', 'highlighter', 'beruf', 'der', 'Textmarker'],
  ['der Radiergummi', 'eraser', 'beruf', 'der', 'Radiergummis'],
  ['das Lineal', 'ruler', 'beruf', 'das', 'Lineale'],
  ['die Schere', 'scissors', 'beruf', 'die', 'Scheren'],
  ['der Computer', 'computer', 'beruf', 'der', 'Computer'],
  ['der PC', 'personal computer', 'beruf', 'der', 'PCs'],
  ['der Laptop', 'laptop', 'beruf', 'der', 'Laptops'],
  ['das Tablet', 'tablet computer', 'beruf', 'das', 'Tablets'],
  ['der Bildschirm / Monitor', 'screen / monitor', 'beruf', 'der', 'Bildschirme'],
  ['die Tastatur', 'keyboard', 'beruf', 'die', 'Tastaturen'],
  ['die Maus', 'mouse (computer)', 'beruf', 'die', 'Mäuse'],
  ['der Drucker', 'printer', 'beruf', 'der', 'Drucker'],
  ['das Ladekabel', 'charging cable', 'beruf', 'das', 'Ladekabel'],
  ['das Dokument', 'document', 'beruf', 'das', 'Dokumente'],
  ['die Datei', 'data file', 'beruf', 'die', 'Dateien'],
  ['der Ordner', 'folder / binder', 'beruf', 'der', 'Ordner'],
  ['die E-Mail / Mail', 'electronic mail', 'beruf', 'die', 'E-Mails'],
  ['der Brief', 'letter', 'beruf', 'der', 'Briefe'],
  ['das Projekt', 'project', 'beruf', 'das', 'Projekte'],
  ['der Termin', 'appointment', 'beruf', 'der', 'Termine'],
  ['die Besprechung / das Meeting', 'meeting / conference', 'beruf', 'die', 'Besprechungen'],
  ['die Konferenz', 'conference', 'beruf', 'die', 'Konferenzen'],
  ['das Protokoll', 'minutes / protocol', 'beruf', 'das', 'Protokolle'],
  ['der Feierabend', 'end of workday', 'beruf', 'der', 'Feierabende'],
  ['die Schicht', 'work shift', 'beruf', 'die', 'Schichten'],
  ['die Überstunde', 'overtime hour', 'beruf', 'die', 'Überstunden'],
  ['der Urlaub', 'vacation / leave', 'beruf', 'der', 'Urlaube'],

  // =========================================================================
  // 6. STADT, VERKEHR & REISEN (Town, Mobility, Transport & Travel)
  // =========================================================================
  ['die Stadt', 'city / town', 'stadt', 'die', 'Städte'],
  ['die Großstadt', 'large city / metropolis', 'stadt', 'die', 'Großstädte'],
  ['die Hauptstadt', 'capital city', 'stadt', 'die', 'Hauptstädte'],
  ['das Dorf', 'village', 'stadt', 'das', 'Dörfer'],
  ['das Zentrum / die Stadtmitte', 'city center / downtown', 'stadt', 'das', 'Zentren'],
  ['die Altstadt', 'historic old town', 'stadt', 'die', 'Altstädte'],
  ['die Straße', 'street / road', 'stadt', 'die', 'Straßen'],
  ['die Autobahn', 'highway / motorway', 'stadt', 'die', 'Autobahnen'],
  ['der Platz', 'square / plaza / place', 'stadt', 'der', 'Plätze'],
  ['der Marktplatz', 'market square', 'stadt', 'der', 'Marktplätze'],
  ['die Kreuzung', 'intersection / junction', 'stadt', 'die', 'Kreuzungen'],
  ['die Ampel', 'traffic light', 'stadt', 'die', 'Ampeln'],
  ['die Ecke', 'corner', 'stadt', 'die', 'Ecken'],
  ['die Brücke', 'bridge', 'stadt', 'die', 'Brücken'],
  ['der Weg', 'way / path / route', 'stadt', 'der', 'Wege'],
  ['der Fußweg / Gehweg', 'sidewalk / pavement', 'stadt', 'der', 'Fußwege'],
  ['die Fußgängerzone', 'pedestrian precinct', 'stadt', 'die', 'Fußgängerzonen'],
  ['der Park', 'public park', 'stadt', 'der', 'Parks'],
  ['der Spielplatz', 'playground', 'stadt', 'der', 'Spielplätze'],
  ['der Bahnhof', 'railway station', 'stadt', 'der', 'Bahnhöfe'],
  ['der Hauptbahnhof', 'central railway station', 'stadt', 'der', 'Hauptbahnhöfe'],
  ['das Gleis', 'platform track', 'stadt', 'das', 'Gleise'],
  ['der Bahnsteig', 'railway platform', 'stadt', 'der', 'Bahnsteige'],
  ['der Schalter', 'ticket / counter window', 'stadt', 'der', 'Schalter'],
  ['der Fahrkartenautomat', 'ticket vending machine', 'stadt', 'der', 'Fahrkartenautomaten'],
  ['die Fahrkarte / der Fahrschein', 'transit ticket', 'stadt', 'die', 'Fahrkarten'],
  ['das Ticket', 'ticket', 'stadt', 'das', 'Tickets'],
  ['die Monatskarte', 'monthly transit pass', 'stadt', 'die', 'Monatskarten'],
  ['die Tageskarte', 'day ticket', 'stadt', 'die', 'Tageskarten'],
  ['der Fahrplan', 'timetable / schedule', 'stadt', 'der', 'Fahrpläne'],
  ['die Abfahrt', 'departure', 'stadt', 'die', 'Abfahrten'],
  ['die Ankunft', 'arrival', 'stadt', 'die', 'Ankünfte'],
  ['die Verspätung', 'delay', 'stadt', 'die', 'Verspätungen'],
  ['die Verbindung', 'connection (transit)', 'stadt', 'die', 'Verbindungen'],
  ['der Umstieg', 'transfer / change of trains', 'stadt', 'der', 'Umstiege'],
  ['die Haltestelle', 'bus/tram stop', 'stadt', 'die', 'Haltestellen'],
  ['der Zug', 'train', 'stadt', 'der', 'Züge'],
  ['der ICE (Intercity-Express)', 'high-speed train', 'stadt', 'der', 'ICEs'],
  ['die Regionalbahn / RB', 'regional train', 'stadt', 'die', 'Regionalbahnen'],
  ['die S-Bahn', 'commuter train', 'stadt', 'die', 'S-Bahnen'],
  ['die U-Bahn', 'underground / subway', 'stadt', 'die', 'U-Bahnen'],
  ['die Straßenbahn / Tram', 'tram / streetcar', 'stadt', 'die', 'Straßenbahnen'],
  ['der Bus', 'bus', 'stadt', 'der', 'Busse'],
  ['das Taxi', 'taxi / cab', 'stadt', 'das', 'Taxis'],
  ['das Auto / der Wagen', 'car / automobile', 'stadt', 'das', 'Autos'],
  ['das Elektroauto', 'electric car', 'stadt', 'das', 'Elektroautos'],
  ['das Fahrrad / Rad', 'bicycle / bike', 'stadt', 'das', 'Fahrräder'],
  ['das E-Bike', 'electric bicycle', 'stadt', 'das', 'E-Bikes'],
  ['der Motorroller / Roller', 'scooter', 'stadt', 'der', 'Roller'],
  ['das Motorrad', 'motorcycle', 'stadt', 'das', 'Motorräder'],
  ['der LKW (Lastkraftwagen)', 'truck / lorry', 'stadt', 'der', 'LKWs'],
  ['das Flugzeug', 'airplane', 'stadt', 'das', 'Flugzeuge'],
  ['der Flughafen', 'airport', 'stadt', 'der', 'Flughäfen'],
  ['der Flug', 'flight', 'stadt', 'der', 'Flüge'],
  ['das Schiff', 'ship', 'stadt', 'das', 'Schiffe'],
  ['die Fähre', 'ferry', 'stadt', 'die', 'Fähren'],
  ['das Boot', 'boat', 'stadt', 'das', 'Boote'],
  ['der Hafen', 'port / harbor', 'stadt', 'der', 'Häfen'],
  ['die Reise', 'journey / voyage', 'stadt', 'die', 'Reisen'],
  ['das Reisebüro', 'travel agency', 'stadt', 'das', 'Reisebüros'],
  ['der Ausflug', 'excursion / day trip', 'stadt', 'der', 'Ausflüge'],
  ['der Stadtplan', 'city map', 'stadt', 'der', 'Stadtpläne'],
  ['die Landkarte', 'geographic map', 'stadt', 'die', 'Landkarten'],
  ['das Navi / Navigationssystem', 'GPS / satnav', 'stadt', 'das', 'Navis'],
  ['das Hotel', 'hotel', 'stadt', 'das', 'Hotels'],
  ['die Pension', 'guest house / B&B', 'stadt', 'die', 'Pensionen'],
  ['die Jugendherberge', 'youth hostel', 'stadt', 'die', 'Jugendherbergen'],
  ['das Zimmer', 'room', 'stadt', 'das', 'Zimmer'],
  ['das Einzelzimmer', 'single room', 'stadt', 'das', 'Einzelzimmer'],
  ['das Doppelzimmer', 'double room', 'stadt', 'das', 'Doppelzimmer'],
  ['die Rezeption', 'reception / front desk', 'stadt', 'die', 'Rezeptionen'],
  ['die Reservierung / Buchung', 'reservation / booking', 'stadt', 'die', 'Reservierungen'],
  ['der Koffer', 'suitcase', 'stadt', 'der', 'Koffer'],
  ['die Tasche', 'bag', 'stadt', 'die', 'Taschen'],
  ['der Rucksack', 'backpack', 'stadt', 'der', 'Rucksäcke'],
  ['das Gepäck', 'luggage / baggage', 'stadt', 'das', '-'],
  ['die Bank / Sparkasse', 'bank / savings bank', 'stadt', 'die', 'Banken'],
  ['der Geldautomat / ATM', 'cash machine / ATM', 'stadt', 'der', 'Geldautomaten'],
  ['das Geld', 'money', 'stadt', 'das', '-'],
  ['die Post', 'post office', 'stadt', 'die', '-'],
  ['die Polizei', 'police station / police', 'stadt', 'die', '-'],
  ['die Feuerwehr', 'fire department', 'stadt', 'die', '-'],
  ['das Bürgeramt / Rathaus', 'citizens office / town hall', 'stadt', 'das', 'Bürgerämter'],
  ['das Konsulat', 'consulate', 'stadt', 'das', 'Konsulate'],
  ['die Botschaft', 'embassy', 'stadt', 'die', 'Botschaften'],
  ['die Kirche', 'church', 'stadt', 'die', 'Kirchen'],
  ['die Moschee', 'mosque', 'stadt', 'die', 'Moscheen'],
  ['die Synagoge', 'synagogue', 'stadt', 'die', 'Synagogen'],
  ['das Museum', 'museum', 'stadt', 'das', 'Museen'],
  ['das Kino', 'cinema / movie theater', 'stadt', 'das', 'Kinos'],
  ['das Theater', 'theater', 'stadt', 'das', 'Theater'],
  ['die Oper', 'opera house', 'stadt', 'die', 'Opern'],
  ['die Bibliothek / Bücherei', 'public library', 'stadt', 'die', 'Bibliotheken'],
  ['das Schwimmbad / Hallenbad', 'swimming pool', 'stadt', 'das', 'Schwimmbäder'],
  ['das Fitnessstudio', 'gym / fitness studio', 'stadt', 'das', 'Fitnessstudios'],
  ['das Schloss', 'castle / palace', 'stadt', 'das', 'Schlösser'],
  ['die Sehenswürdigkeit', 'sight / tourist attraction', 'stadt', 'die', 'Sehenswürdigkeiten'],

  // =========================================================================
  // 7. GESUNDHEIT, KÖRPER & HYGIENE (Body, Health & Medicine)
  // =========================================================================
  ['der Körper', 'body', 'gesundheit', 'der', 'Körper'],
  ['der Kopf', 'head', 'gesundheit', 'der', 'Köpfe'],
  ['das Haar / die Haare', 'hair', 'gesundheit', 'das', 'Haare'],
  ['das Gesicht', 'face', 'gesundheit', 'das', 'Gesichter'],
  ['das Auge', 'eye', 'gesundheit', 'das', 'Augen'],
  ['das Ohr', 'ear', 'gesundheit', 'das', 'Ohren'],
  ['die Nase', 'nose', 'gesundheit', 'die', 'Nasen'],
  ['der Mund', 'mouth', 'gesundheit', 'der', 'Münder'],
  ['die Lippe', 'lip', 'gesundheit', 'die', 'Lippen'],
  ['der Zahn', 'tooth', 'gesundheit', 'der', 'Zähne'],
  ['die Zunge', 'tongue', 'gesundheit', 'die', 'Zungen'],
  ['der Hals', 'throat / neck', 'gesundheit', 'der', 'Hälse'],
  ['die Schulter', 'shoulder', 'gesundheit', 'die', 'Schultern'],
  ['die Brust', 'chest / breast', 'gesundheit', 'die', 'Brüste'],
  ['der Rücken', 'back', 'gesundheit', 'der', 'Rücken'],
  ['der Bauch', 'belly / abdomen', 'gesundheit', 'der', 'Bäuche'],
  ['der Magen', 'stomach', 'gesundheit', 'der', 'Mägen'],
  ['das Herz', 'heart', 'gesundheit', 'das', 'Herzen'],
  ['der Arm', 'arm', 'gesundheit', 'der', 'Arme'],
  ['die Hand', 'hand', 'gesundheit', 'die', 'Hände'],
  ['der Finger', 'finger', 'gesundheit', 'der', 'Finger'],
  ['der Daumen', 'thumb', 'gesundheit', 'der', 'Daumen'],
  ['das Bein', 'leg', 'gesundheit', 'das', 'Beine'],
  ['das Knie', 'knee', 'gesundheit', 'das', 'Knie'],
  ['der Fuß', 'foot', 'gesundheit', 'der', 'Füße'],
  ['der Zeh / die Zehe', 'toe', 'gesundheit', 'der', 'Zehen'],
  ['die Haut', 'skin', 'gesundheit', 'die', '-'],
  ['der Blutdruck', 'blood pressure', 'gesundheit', 'der', '-'],
  ['das Blut', 'blood', 'gesundheit', 'das', '-'],
  ['die Gesundheit', 'health', 'gesundheit', 'die', '-'],
  ['die Krankheit', 'illness / disease', 'gesundheit', 'die', 'Krankheiten'],
  ['der Schmerz', 'pain / ache', 'gesundheit', 'der', 'Schmerzen'],
  ['die Kopfschmerzen', 'headache', 'gesundheit', 'die', 'Kopfschmerzen'],
  ['die Bauchschmerzen / Magenschmerzen', 'stomach ache', 'gesundheit', 'die', 'Bauchschmerzen'],
  ['die Halsschmerzen', 'sore throat', 'gesundheit', 'die', 'Halsschmerzen'],
  ['die Zahnschmerzen', 'toothache', 'gesundheit', 'die', 'Zahnschmerzen'],
  ['die Rückenschmerzen', 'back pain', 'gesundheit', 'die', 'Rückenschmerzen'],
  ['das Fieber', 'fever', 'gesundheit', 'das', '-'],
  ['das Thermometer', 'thermometer', 'gesundheit', 'das', 'Thermometer'],
  ['der Husten', 'cough', 'gesundheit', 'der', '-'],
  ['der Schnupfen', 'runny nose / head cold', 'gesundheit', 'der', '-'],
  ['die Grippe', 'influenza / flu', 'gesundheit', 'die', '-'],
  ['die Erkältung', 'common cold', 'gesundheit', 'die', 'Erkältungen'],
  ['die Allergie', 'allergy', 'gesundheit', 'die', 'Allergien'],
  ['die Wunde', 'wound / cut', 'gesundheit', 'die', 'Wunden'],
  ['der Unfall', 'accident', 'gesundheit', 'der', 'Unfälle'],
  ['der Notfall', 'emergency', 'gesundheit', 'der', 'Notfälle'],
  ['der Notarzt', 'emergency physician', 'gesundheit', 'der', 'Notärzte'],
  ['der Krankenwagen / Rettungswagen', 'ambulance', 'gesundheit', 'der', 'Krankenwagen'],
  ['das Krankenhaus / die Klinik', 'hospital', 'gesundheit', 'das', 'Krankenhäuser'],
  ['die Praxis / Arztpraxis', 'doctor\'s surgery / practice', 'gesundheit', 'die', 'Praxen'],
  ['das Wartezimmer', 'waiting room', 'gesundheit', 'das', 'Wartezimmer'],
  ['die Sprechstunde', 'office consultation hours', 'gesundheit', 'die', 'Sprechstunden'],
  ['der Termin', 'appointment', 'gesundheit', 'der', 'Termine'],
  ['die Versichertenkarte', 'health insurance card', 'gesundheit', 'die', 'Versichertenkarten'],
  ['die Krankenkasse', 'health insurance company', 'gesundheit', 'die', 'Krankenkassen'],
  ['das Rezept', 'medical prescription', 'gesundheit', 'das', 'Rezepte'],
  ['die Krankmeldung / das Attest', 'sick leave certificate', 'gesundheit', 'die', 'Krankmeldungen'],
  ['die Apotheke', 'pharmacy / chemist', 'gesundheit', 'die', 'Apotheken'],
  ['der Apotheker', 'pharmacist (male)', 'gesundheit', 'der', 'Apotheker'],
  ['das Medikament / die Arznei', 'medication / medicine', 'gesundheit', 'das', 'Medikamente'],
  ['die Tablette', 'pill / tablet', 'gesundheit', 'die', 'Tabletten'],
  ['die Pille', 'pill', 'gesundheit', 'die', 'Pillen'],
  ['die Tropfen', 'drops (medicine)', 'gesundheit', 'die', 'Tropfen'],
  ['der Hustensaft', 'cough syrup', 'gesundheit', 'der', 'Hustensäfte'],
  ['die Salbe / Creme', 'ointment / cream', 'gesundheit', 'die', 'Salben'],
  ['das Pflaster', 'adhesive bandage / plaster', 'gesundheit', 'das', 'Pflaster'],
  ['der Verband', 'bandage / dressing', 'gesundheit', 'der', 'Verbände'],
  ['die Spritze', 'injection / syringe', 'gesundheit', 'die', 'Spritzen'],
  ['die Brille', 'spectacles / glasses', 'gesundheit', 'die', 'Brillen'],

  // =========================================================================
  // 8. FREIZEIT, HOBBYS & WETTER (Leisure, Hobbies & Weather)
  // =========================================================================
  ['die Freizeit', 'free time / leisure', 'freizeit', 'die', '-'],
  ['das Hobby', 'hobby', 'freizeit', 'das', 'Hobbys'],
  ['das Interesse', 'interest', 'freizeit', 'das', 'Interessen'],
  ['der Sport', 'sport / athletics', 'freizeit', 'der', '-'],
  ['der Fußball', 'football / soccer', 'freizeit', 'der', 'Fußbälle'],
  ['das Tennis', 'tennis', 'freizeit', 'das', '-'],
  ['das Schwimmen', 'swimming', 'freizeit', 'das', '-'],
  ['das Fahrradfahren / Radfahren', 'cycling', 'freizeit', 'das', '-'],
  ['das Wandern', 'hiking', 'freizeit', 'das', '-'],
  ['das Joggen / Laufen', 'jogging / running', 'freizeit', 'das', '-'],
  ['das Tanzen', 'dancing', 'freizeit', 'das', '-'],
  ['das Kochen', 'cooking', 'freizeit', 'das', '-'],
  ['das Lesen', 'reading', 'freizeit', 'das', '-'],
  ['die Musik', 'music', 'freizeit', 'die', '-'],
  ['das Lied / der Song', 'song', 'freizeit', 'das', 'Lieder'],
  ['die Band / Gruppe', 'band / musical group', 'freizeit', 'die', 'Bands'],
  ['das Konzert', 'concert', 'freizeit', 'das', 'Konzerte'],
  ['die Gitarre', 'guitar', 'freizeit', 'die', 'Gitarren'],
  ['das Klavier', 'piano', 'freizeit', 'das', 'Klaviere'],
  ['das Spiel', 'game / match', 'freizeit', 'das', 'Spiele'],
  ['das Kartenspiel', 'card game', 'freizeit', 'das', 'Kartenspiele'],
  ['das Computerspiel', 'video game', 'freizeit', 'das', 'Computerspiele'],
  ['der Film', 'film / movie', 'freizeit', 'der', 'Filme'],
  ['das Kino', 'cinema', 'freizeit', 'das', 'Kinos'],
  ['das Theater', 'theatre', 'freizeit', 'das', 'Theater'],
  ['das Museum', 'museum', 'freizeit', 'das', 'Museen'],
  ['die Ausstellung', 'exhibition', 'freizeit', 'die', 'Ausstellungen'],
  ['die Party / Fete', 'party', 'freizeit', 'die', 'Partys'],
  ['das Fest / die Feier', 'celebration / festival', 'freizeit', 'das', 'Feste'],
  ['der Geburtstag', 'birthday', 'freizeit', 'der', 'Geburtstage'],
  ['die Hochzeit', 'wedding', 'freizeit', 'die', 'Hochzeiten'],
  ['das Jubiläum', 'anniversary', 'freizeit', 'das', 'Jubiläen'],
  ['das Geschenk', 'present / gift', 'freizeit', 'das', 'Geschenke'],
  ['die Einladung', 'invitation', 'freizeit', 'die', 'Einladungen'],
  ['der Urlaub', 'holiday / vacation', 'freizeit', 'der', 'Urlaube'],
  ['die Ferien', 'school holidays / recess', 'freizeit', 'die', 'Ferien'],
  ['die Natur', 'nature', 'freizeit', 'die', '-'],
  ['das Meer / die See', 'sea / ocean', 'freizeit', 'das', 'Meere'],
  ['der Strand', 'beach', 'freizeit', 'der', 'Strände'],
  ['der See', 'lake', 'freizeit', 'der', 'Seen'],
  ['der Fluss', 'river', 'freizeit', 'der', 'Flüsse'],
  ['der Berg', 'mountain', 'freizeit', 'der', 'Berge'],
  ['die Berge / Alpen', 'mountains / Alps', 'freizeit', 'die', 'Berge'],
  ['der Wald', 'forest / woods', 'freizeit', 'der', 'Wälder'],
  ['der Baum', 'tree', 'freizeit', 'der', 'Bäume'],
  ['die Blume', 'flower', 'freizeit', 'die', 'Blumen'],
  ['die Pflanze', 'plant', 'freizeit', 'die', 'Pflanzen'],
  ['das Tier', 'animal', 'freizeit', 'das', 'Tiere'],
  ['der Hund', 'dog', 'freizeit', 'der', 'Hunde'],
  ['die Katze', 'cat', 'freizeit', 'die', 'Katzen'],
  ['der Vogel', 'bird', 'freizeit', 'der', 'Vögel'],
  ['das Wetter', 'weather', 'freizeit', 'das', '-'],
  ['die Wettervorhersage / der Wetterbericht', 'weather forecast', 'freizeit', 'die', 'Wetterberichte'],
  ['die Sonne', 'sun', 'freizeit', 'die', '-'],
  ['der Sonnenschein', 'sunshine', 'freizeit', 'der', '-'],
  ['der Regen', 'rain', 'freizeit', 'der', '-'],
  ['der Schnee', 'snow', 'freizeit', 'der', '-'],
  ['das Eis', 'ice', 'freizeit', 'das', '-'],
  ['der Wind', 'wind', 'freizeit', 'der', 'Winde'],
  ['der Sturm', 'storm / gale', 'freizeit', 'der', 'Stürme'],
  ['das Gewitter', 'thunderstorm', 'freizeit', 'das', 'Gewitter'],
  ['der Blitz', 'lightning bolt', 'freizeit', 'der', 'Blitze'],
  ['der Donner', 'thunder', 'freizeit', 'der', '-'],
  ['die Wolke', 'cloud', 'freizeit', 'die', 'Wolken'],
  ['der Nebel', 'fog / mist', 'freizeit', 'der', '-'],
  ['der Himmel', 'sky / heaven', 'freizeit', 'der', '-'],
  ['die Temperatur', 'temperature', 'freizeit', 'die', 'Temperaturen'],
  ['das Grad', 'degree (temperature)', 'freizeit', 'das', 'Grad'],

  // =========================================================================
  // 9. KLEIDUNG & SHOPPING (Clothing, Shopping & Consumer Goods)
  // =========================================================================
  ['die Kleidung', 'clothing / clothes', 'kleidung', 'die', '-'],
  ['die Klamotten', 'clothes (casual)', 'kleidung', 'die', 'Klamotten'],
  ['die Hose', 'pants / trousers', 'kleidung', 'die', 'Hosen'],
  ['die Jeans', 'jeans', 'kleidung', 'die', 'Jeans'],
  ['die Kurze Hose / Shorts', 'shorts', 'kleidung', 'die', 'Shorts'],
  ['das Hemd', 'shirt', 'kleidung', 'das', 'Hemden'],
  ['die Bluse', 'blouse', 'kleidung', 'die', 'Blusen'],
  ['das T-Shirt', 't-shirt', 'kleidung', 'das', 'T-Shirts'],
  ['das Polohemd', 'polo shirt', 'kleidung', 'das', 'Polohemden'],
  ['der Pullover / Pulli', 'sweater / jumper', 'kleidung', 'der', 'Pullover'],
  ['die Strickjacke', 'cardigan', 'kleidung', 'die', 'Strickjacken'],
  ['die Jacke', 'jacket', 'kleidung', 'die', 'Jacken'],
  ['der Mantel', 'coat', 'kleidung', 'der', 'Mäntel'],
  ['der Regenmantel', 'raincoat', 'kleidung', 'der', 'Regenmäntel'],
  ['der Anzug', 'suit (men)', 'kleidung', 'der', 'Anzüge'],
  ['das Kostüm', 'suit (women) / costume', 'kleidung', 'das', 'Kostüme'],
  ['das Kleid', 'dress', 'kleidung', 'das', 'Kleider'],
  ['der Rock', 'skirt', 'kleidung', 'der', 'Röcke'],
  ['der Schuh', 'shoe', 'kleidung', 'der', 'Schuhe'],
  ['die Sportschuhe / Turnschuhe', 'sneakers / sports shoes', 'kleidung', 'die', 'Sportschuhe'],
  ['die Stiefel', 'boots', 'kleidung', 'die', 'Stiefel'],
  ['die Sandale', 'sandal', 'kleidung', 'die', 'Sandalen'],
  ['die Socke', 'sock', 'kleidung', 'die', 'Socken'],
  ['der Strumpf', 'stocking', 'kleidung', 'der', 'Strümpfe'],
  ['die Unterwäsche', 'underwear', 'kleidung', 'die', '-'],
  ['die Unterhose', 'underpants', 'kleidung', 'die', 'Unterhosen'],
  ['das Unterhemd', 'undershirt / vest', 'kleidung', 'das', 'Unterhemden'],
  ['der Schlafanzug / Pyjama', 'pajamas', 'kleidung', 'der', 'Schlafanzüge'],
  ['die Mütze', 'beanie / winter cap', 'kleidung', 'die', 'Mützen'],
  ['der Hut', 'hat', 'kleidung', 'der', 'Hüte'],
  ['die Kappe / das Cappy', 'cap / baseball cap', 'kleidung', 'die', 'Kappen'],
  ['der Schal', 'scarf', 'kleidung', 'der', 'Schals'],
  ['die Handschuhe', 'gloves', 'kleidung', 'die', 'Handschuhe'],
  ['der Gürtel', 'belt', 'kleidung', 'der', 'Gürtel'],
  ['die Krawatte', 'necktie', 'kleidung', 'die', 'Krawatten'],
  ['die Fliege', 'bow tie', 'kleidung', 'die', 'Fliegen'],
  ['die Tasche', 'handbag / bag', 'kleidung', 'die', 'Taschen'],
  ['die Handtasche', 'handbag / purse', 'kleidung', 'die', 'Handtaschen'],
  ['das Portemonnaie / die Geldbörse', 'wallet / purse', 'kleidung', 'das', 'Portemonnaies'],
  ['der Regenschirm', 'umbrella', 'kleidung', 'der', 'Regenschirme'],
  ['die Sonnenbrille', 'sunglasses', 'kleidung', 'die', 'Sonnenbrillen'],
  ['der Schmuck', 'jewellery', 'kleidung', 'der', '-'],
  ['der Ring', 'ring', 'kleidung', 'der', 'Ringe'],
  ['die Kette / Halskette', 'necklace / chain', 'kleidung', 'die', 'Ketten'],
  ['die Uhr / Armbanduhr', 'wrist watch', 'kleidung', 'die', 'Uhren'],
  ['die Größe', 'clothing size', 'kleidung', 'die', 'Größen'],
  ['die Farbe', 'color', 'kleidung', 'die', 'Farben'],
  ['die Baumwolle', 'cotton', 'kleidung', 'die', '-'],
  ['die Wolle', 'wool', 'kleidung', 'die', '-'],
  ['das Leder', 'leather', 'kleidung', 'das', '-'],
  ['das Geschäft / der Laden', 'shop / store', 'kleidung', 'das', 'Geschäfte'],
  ['das Kaufhaus / Warenhaus', 'department store', 'kleidung', 'das', 'Kaufhäuser'],
  ['das Einkaufszentrum / die Mall', 'shopping mall', 'kleidung', 'das', 'Einkaufszentren'],
  ['die Kasse', 'cash desk / checkout', 'kleidung', 'die', 'Kassen'],
  ['die Umkleidekabine', 'changing cubicle / fitting room', 'kleidung', 'die', 'Umkleidekabinen'],
  ['das Sonderangebot', 'special offer / bargain', 'kleidung', 'das', 'Sonderangebote'],
  ['der Rabatt', 'discount', 'kleidung', 'der', 'Rabatte'],
  ['der Kassenzettel / der Beleg', 'receipt / proof of purchase', 'kleidung', 'der', 'Kassenzettel'],
  ['die Garantie', 'warranty / guarantee', 'kleidung', 'die', 'Garantien'],

  // =========================================================================
  // 10. ZEIT, KALENDER & ZEITADVERBIEN (Time, Calendar & Temporal Terms)
  // =========================================================================
  ['die Zeit', 'time', 'zeit', 'die', 'Zeiten'],
  ['die Uhrzeit', 'clock time', 'zeit', 'die', 'Uhrzeiten'],
  ['die Sekunde', 'second', 'zeit', 'die', 'Sekunden'],
  ['die Minute', 'minute', 'zeit', 'die', 'Minuten'],
  ['die Viertelstunde', 'quarter of an hour', 'zeit', 'die', 'Viertelstunden'],
  ['die halbe Stunde', 'half an hour', 'zeit', 'die', 'halben Stunden'],
  ['die Stunde', 'hour', 'zeit', 'die', 'Stunden'],
  ['der Tag', 'day', 'zeit', 'der', 'Tage'],
  ['die Woche', 'week', 'zeit', 'die', 'Wochen'],
  ['der Monat', 'month', 'zeit', 'der', 'Monate'],
  ['das Jahr', 'year', 'zeit', 'das', 'Jahre'],
  ['das Jahrzehnt', 'decade', 'zeit', 'das', 'Jahrzehnte'],
  ['das Jahrhundert', 'century', 'zeit', 'das', 'Jahrhunderte'],
  ['das Datum', 'calendar date', 'zeit', 'das', 'Daten'],
  ['der Kalender', 'calendar', 'zeit', 'der', 'Kalender'],
  ['der Feiertag', 'public holiday', 'zeit', 'der', 'Feiertage'],
  ['der Werktag / Arbeitstag', 'working day / weekday', 'zeit', 'der', 'Werktage'],
  ['das Wochenende', 'weekend', 'zeit', 'das', 'Wochenenden'],
  ['der Morgen', 'morning', 'zeit', 'der', 'Morgen'],
  ['der Vormittag', 'late morning', 'zeit', 'der', 'Vormittage'],
  ['der Mittag', 'noon / midday', 'zeit', 'der', 'Mittage'],
  ['der Nachmittag', 'afternoon', 'zeit', 'der', 'Nachmittage'],
  ['der Abend', 'evening', 'zeit', 'der', 'Abende'],
  ['die Nacht', 'night', 'zeit', 'die', 'Nächte'],
  ['die Mitternacht', 'midnight', 'zeit', 'die', '-'],
  ['der Montag', 'Monday', 'zeit', 'der', 'Montage'],
  ['der Dienstag', 'Tuesday', 'zeit', 'der', 'Dienstage'],
  ['der Mittwoch', 'Wednesday', 'zeit', 'der', 'Mittwoche'],
  ['der Donnerstag', 'Thursday', 'zeit', 'der', 'Donnerstage'],
  ['der Freitag', 'Friday', 'zeit', 'der', 'Freitage'],
  ['der Samstag / Sonnabend', 'Saturday', 'zeit', 'der', 'Samstage'],
  ['der Sonntag', 'Sunday', 'zeit', 'der', 'Sonntage'],
  ['der Januar', 'January', 'zeit', 'der', '-'],
  ['der Februar', 'February', 'zeit', 'der', '-'],
  ['der März', 'March', 'zeit', 'der', '-'],
  ['der April', 'April', 'zeit', 'der', '-'],
  ['der Mai', 'May', 'zeit', 'der', '-'],
  ['der Juni', 'June', 'zeit', 'der', '-'],
  ['der Juli', 'July', 'zeit', 'der', '-'],
  ['der August', 'August', 'zeit', 'der', '-'],
  ['der September', 'September', 'zeit', 'der', '-'],
  ['der Oktober', 'October', 'zeit', 'der', '-'],
  ['der November', 'November', 'zeit', 'der', '-'],
  ['der Dezember', 'December', 'zeit', 'der', '-'],
  ['die Jahreszeit', 'season (climate)', 'zeit', 'die', 'Jahreszeiten'],
  ['der Frühling / das Frühjahr', 'spring', 'zeit', 'der', '-'],
  ['der Sommer', 'summer', 'zeit', 'der', 'Sommer'],
  ['der Herbst', 'autumn / fall', 'zeit', 'der', 'Herbste'],
  ['der Winter', 'winter', 'zeit', 'der', 'Winter'],
  ['gestern', 'yesterday', 'zeit', null, '-'],
  ['vorgestern', 'day before yesterday', 'zeit', null, '-'],
  ['heute', 'today', 'zeit', null, '-'],
  ['morgen', 'tomorrow', 'zeit', null, '-'],
  ['übermorgen', 'day after tomorrow', 'zeit', null, '-'],
  ['jetzt / nun', 'now / at present', 'zeit', null, '-'],
  ['gerade / im Moment', 'right now / currently', 'zeit', null, '-'],
  ['gleich / sofort', 'right away / immediately', 'zeit', null, '-'],
  ['bald', 'soon', 'zeit', null, '-'],
  ['später', 'later', 'zeit', null, '-'],
  ['früher', 'earlier / formerly', 'zeit', null, '-'],
  ['immer', 'always', 'zeit', null, '-'],
  ['meistens / meist', 'mostly / usually', 'zeit', null, '-'],
  ['oft / häufig', 'often / frequently', 'zeit', null, '-'],
  ['manchmal', 'sometimes', 'zeit', null, '-'],
  ['selten', 'rarely / seldom', 'zeit', null, '-'],
  ['nie / niemals', 'never', 'zeit', null, '-'],
  ['schon / bereits', 'already', 'zeit', null, '-'],
  ['noch', 'still / yet', 'zeit', null, '-'],
  ['noch nicht', 'not yet', 'zeit', null, '-'],
  ['nicht mehr', 'no longer / not anymore', 'zeit', null, '-'],
  ['zuerst', 'at first / first of all', 'zeit', null, '-'],
  ['dann', 'then', 'zeit', null, '-'],
  ['danach', 'after that / afterwards', 'zeit', null, '-'],
  ['schließlich / zum Schluss', 'finally / in the end', 'zeit', null, '-'],

  // =========================================================================
  // 11. ADJEKTIVE & ADVERBIEN (Core A1 Qualifiers, Opposites & Colors)
  // =========================================================================
  ['gut', 'good / well', 'adjektive', null, '-'],
  ['schlecht', 'bad / poor', 'adjektive', null, '-'],
  ['groß', 'big / tall / large', 'adjektive', null, '-'],
  ['klein', 'small / little', 'adjektive', null, '-'],
  ['neu', 'new', 'adjektive', null, '-'],
  ['alt', 'old', 'adjektive', null, '-'],
  ['jung', 'young', 'adjektive', null, '-'],
  ['schön', 'beautiful / pretty / fine', 'adjektive', null, '-'],
  ['hässlich', 'ugly', 'adjektive', null, '-'],
  ['hell', 'bright / light', 'adjektive', null, '-'],
  ['dunkel', 'dark', 'adjektive', null, '-'],
  ['warm', 'warm', 'adjektive', null, '-'],
  ['heiß', 'hot', 'adjektive', null, '-'],
  ['kalt', 'cold', 'adjektive', null, '-'],
  ['kühl', 'cool', 'adjektive', null, '-'],
  ['frisch', 'fresh', 'adjektive', null, '-'],
  ['sauber', 'clean', 'adjektive', null, '-'],
  ['schmutzig / dreckig', 'dirty', 'adjektive', null, '-'],
  ['laut', 'loud / noisy', 'adjektive', null, '-'],
  ['leise / ruhig', 'quiet / calm', 'adjektive', null, '-'],
  ['schnell', 'fast / quick', 'adjektive', null, '-'],
  ['langsam', 'slow', 'adjektive', null, '-'],
  ['früh', 'early', 'adjektive', null, '-'],
  ['spät', 'late', 'adjektive', null, '-'],
  ['pünktlich', 'punctual / on time', 'adjektive', null, '-'],
  ['unpünktlich', 'unpunctual / late', 'adjektive', null, '-'],
  ['teuer', 'expensive', 'adjektive', null, '-'],
  ['billig / preiswert / günstig', 'cheap / affordable', 'adjektive', null, '-'],
  ['kostenlos / umsonst / gratis', 'free of charge', 'adjektive', null, '-'],
  ['einfach / leicht', 'simple / easy / light', 'adjektive', null, '-'],
  ['schwer / schwierig', 'heavy / difficult / hard', 'adjektive', null, '-'],
  ['richtig / korrekt', 'correct / right', 'adjektive', null, '-'],
  ['falsch', 'wrong / incorrect', 'adjektive', null, '-'],
  ['wichtig', 'important', 'adjektive', null, '-'],
  ['unwichtig', 'unimportant', 'adjektive', null, '-'],
  ['gesund', 'healthy', 'adjektive', null, '-'],
  ['krank', 'ill / sick', 'adjektive', null, '-'],
  ['müde', 'tired', 'adjektive', null, '-'],
  ['fit', 'fit / active', 'adjektive', null, '-'],
  ['stark', 'strong', 'adjektive', null, '-'],
  ['schwach', 'weak', 'adjektive', null, '-'],
  ['offen / geöffnet', 'open', 'adjektive', null, '-'],
  ['zu / geschlossen', 'closed', 'adjektive', null, '-'],
  ['frei', 'vacant / free', 'adjektive', null, '-'],
  ['besetzt', 'occupied / taken', 'adjektive', null, '-'],
  ['voll', 'full', 'adjektive', null, '-'],
  ['leer', 'empty', 'adjektive', null, '-'],
  ['fertig', 'finished / ready', 'adjektive', null, '-'],
  ['kaputt / defekt', 'broken / out of order', 'adjektive', null, '-'],
  ['ganz', 'whole / intact / complete', 'adjektive', null, '-'],
  ['lecker / köstlich', 'delicious / tasty', 'adjektive', null, '-'],
  ['süß', 'sweet / cute', 'adjektive', null, '-'],
  ['sauer', 'sour / angry', 'adjektive', null, '-'],
  ['salzig', 'salty', 'adjektive', null, '-'],
  ['scharf', 'spicy / sharp', 'adjektive', null, '-'],
  ['bitter', 'bitter', 'adjektive', null, '-'],
  ['ledig', 'single / unmarried', 'adjektive', null, '-'],
  ['verheiratet', 'married', 'adjektive', null, '-'],
  ['geschieden', 'divorced', 'adjektive', null, '-'],
  ['verwitwet', 'widowed', 'adjektive', null, '-'],
  ['freundlich / nett', 'friendly / kind', 'adjektive', null, '-'],
  ['unfreundlich', 'unfriendly', 'adjektive', null, '-'],
  ['höflich', 'polite', 'adjektive', null, '-'],
  ['unhöflich', 'impolite / rude', 'adjektive', null, '-'],
  ['lustig / witzig', 'funny / amusing', 'adjektive', null, '-'],
  ['traurig', 'sad', 'adjektive', null, '-'],
  ['glücklich / froh', 'happy / glad', 'adjektive', null, '-'],
  ['sympathisch', 'likeable / pleasant', 'adjektive', null, '-'],
  ['interessant', 'interesting', 'adjektive', null, '-'],
  ['langweilig', 'boring', 'adjektive', null, '-'],
  ['tolle / super / prima', 'great / wonderful', 'adjektive', null, '-'],
  ['schrecklich', 'terrible / awful', 'adjektive', null, '-'],
  ['nah / in der Nähe', 'near / nearby', 'adjektive', null, '-'],
  ['weit / entfernt', 'far / distant', 'adjektive', null, '-'],
  ['links', 'left', 'adjektive', null, '-'],
  ['rechts', 'right', 'adjektive', null, '-'],
  ['geradeaus', 'straight ahead', 'adjektive', null, '-'],
  ['oben', 'above / upstairs', 'adjektive', null, '-'],
  ['unten', 'below / downstairs', 'adjektive', null, '-'],
  ['vorn / vorne', 'in front / at the front', 'adjektive', null, '-'],
  ['hinten', 'in the back / behind', 'adjektive', null, '-'],
  ['drinnen', 'inside / indoors', 'adjektive', null, '-'],
  ['draußen', 'outside / outdoors', 'adjektive', null, '-'],
  ['hier', 'here', 'adjektive', null, '-'],
  ['da / dort', 'there', 'adjektive', null, '-'],
  ['drüben', 'over there', 'adjektive', null, '-'],
  ['rot', 'red', 'adjektive', null, '-'],
  ['blau', 'blue', 'adjektive', null, '-'],
  ['grün', 'green', 'adjektive', null, '-'],
  ['gelb', 'yellow', 'adjektive', null, '-'],
  ['schwarz', 'black', 'adjektive', null, '-'],
  ['weiß', 'white', 'adjektive', null, '-'],
  ['grau', 'grey', 'adjektive', null, '-'],
  ['braun', 'brown', 'adjektive', null, '-'],
  ['orange', 'orange (color)', 'adjektive', null, '-'],
  ['rosa / pink', 'pink', 'adjektive', null, '-'],
  ['lila / violett', 'purple / violet', 'adjektive', null, '-'],
  ['viel', 'much / a lot', 'adjektive', null, '-'],
  ['wenig', 'little / few', 'adjektive', null, '-'],
  ['mehr', 'more', 'adjektive', null, '-'],
  ['genug', 'enough', 'adjektive', null, '-'],
  ['sehr', 'very', 'adjektive', null, '-'],
  ['zu (zu groß/teuer)', 'too (too big/expensive)', 'adjektive', null, '-'],
  ['besonders', 'especially / particularly', 'adjektive', null, '-'],
  ['ziemlich', 'quite / rather', 'adjektive', null, '-'],
  ['etwas / ein bisschen', 'a little / somewhat', 'adjektive', null, '-'],
  ['wirklich / echt', 'really / genuinely', 'adjektive', null, '-'],
  ['sicher / bestimmt', 'certainly / surely', 'adjektive', null, '-'],
  ['vielleicht', 'maybe / perhaps', 'adjektive', null, '-'],
  ['wahrscheinlich', 'probably', 'adjektive', null, '-'],
  ['zusammen / gemeinsam', 'together', 'adjektive', null, '-'],
  ['allein / alleine', 'alone', 'adjektive', null, '-'],

  // =========================================================================
  // 12. KERNE A1 VERBEN (Core A1 Action, Auxiliary, Modal & Separable Verbs)
  // =========================================================================
  ['sein', 'to be', 'verben', null, '-'],
  ['haben', 'to have', 'verben', null, '-'],
  ['werden', 'to become', 'verben', null, '-'],
  ['können', 'can / to be able to', 'verben', null, '-'],
  ['müssen', 'must / to have to', 'verben', null, '-'],
  ['dürfen', 'may / to be allowed to', 'verben', null, '-'],
  ['wollen', 'to want / intend', 'verben', null, '-'],
  ['sollen', 'should / supposed to', 'verben', null, '-'],
  ['mögen', 'to like (food/things)', 'verben', null, '-'],
  ['möchten', 'would like to', 'verben', null, '-'],
  ['machen', 'to make / do', 'verben', null, '-'],
  ['tun', 'to do', 'verben', null, '-'],
  ['lernen', 'to learn / study', 'verben', null, '-'],
  ['studieren', 'to study at university', 'verben', null, '-'],
  ['arbeiten', 'to work', 'verben', null, '-'],
  ['wohnen', 'to reside / live in', 'verben', null, '-'],
  ['leben', 'to live', 'verben', null, '-'],
  ['heißen', 'to be called / named', 'verben', null, '-'],
  ['kommen', 'to come / arrive', 'verben', null, '-'],
  ['gehen', 'to go / walk', 'verben', null, '-'],
  ['fahren', 'to drive / ride', 'verben', null, '-'],
  ['fliegen', 'to fly', 'verben', null, '-'],
  ['reisen', 'to travel', 'verben', null, '-'],
  ['laufen', 'to run / walk', 'verben', null, '-'],
  ['schwimmen', 'to swim', 'verben', null, '-'],
  ['wandern', 'to hike', 'verben', null, '-'],
  ['spazieren gehen', 'to go for a walk', 'verben', null, '-'],
  ['bleiben', 'to stay / remain', 'verben', null, '-'],
  ['stehen', 'to stand', 'verben', null, '-'],
  ['sitzen', 'to sit', 'verben', null, '-'],
  ['liegen', 'to lie / be situated', 'verben', null, '-'],
  ['stellen', 'to put / place upright', 'verben', null, '-'],
  ['legen', 'to lay / put horizontally', 'verben', null, '-'],
  ['setzen', 'to set / sit down', 'verben', null, '-'],
  ['hängen', 'to hang', 'verben', null, '-'],
  ['sehen', 'to see', 'verben', null, '-'],
  ['schauen / gucken', 'to look / watch', 'verben', null, '-'],
  ['hören', 'to hear / listen', 'verben', null, '-'],
  ['zuhören', 'to listen attentively', 'verben', null, '-'],
  ['riechen', 'to smell', 'verben', null, '-'],
  ['schmecken', 'to taste (good)', 'verben', null, '-'],
  ['fühlen', 'to feel', 'verben', null, '-'],
  ['sprechen', 'to speak / talk', 'verben', null, '-'],
  ['sagen', 'to say / tell', 'verben', null, '-'],
  ['erzählen', 'to narrate / recount', 'verben', null, '-'],
  ['reden', 'to talk / chat', 'verben', null, '-'],
  ['fragen', 'to ask', 'verben', null, '-'],
  ['antworten', 'to answer / reply', 'verben', null, '-'],
  ['lesen', 'to read', 'verben', null, '-'],
  ['schreiben', 'to write', 'verben', null, '-'],
  ['buchstabieren', 'to spell out letters', 'verben', null, '-'],
  ['wiederholen', 'to repeat', 'verben', null, '-'],
  ['verstehen', 'to understand', 'verben', null, '-'],
  ['wissen', 'to know facts', 'verben', null, '-'],
  ['kennen', 'to be acquainted with', 'verben', null, '-'],
  ['kennenlernen', 'to get to know', 'verben', null, '-'],
  ['denken', 'to think', 'verben', null, '-'],
  ['glauben', 'to believe', 'verben', null, '-'],
  ['meinen', 'to mean / think', 'verben', null, '-'],
  ['hoffen', 'to hope', 'verben', null, '-'],
  ['essen', 'to eat', 'verben', null, '-'],
  ['trinken', 'to drink', 'verben', null, '-'],
  ['kochen', 'to cook / boil', 'verben', null, '-'],
  ['backen', 'to bake', 'verben', null, '-'],
  ['braten', 'to fry / roast', 'verben', null, '-'],
  ['frühstücken', 'to have breakfast', 'verben', null, '-'],
  ['probieren', 'to taste / try', 'verben', null, '-'],
  ['schlafen', 'to sleep', 'verben', null, '-'],
  ['einschlafen', 'to fall asleep', 'verben', null, '-'],
  ['aufwachen', 'to wake up', 'verben', null, '-'],
  ['aufstehen', 'to get up / stand up', 'verben', null, '-'],
  ['duschen', 'to take a shower', 'verben', null, '-'],
  ['baden', 'to take a bath', 'verben', null, '-'],
  ['waschen', 'to wash', 'verben', null, '-'],
  ['putzen', 'to clean / brush', 'verben', null, '-'],
  ['aufräumen', 'to tidy up / clean up', 'verben', null, '-'],
  ['anziehen', 'to put on clothes', 'verben', null, '-'],
  ['ausziehen', 'to take off clothes / move out', 'verben', null, '-'],
  ['umziehen', 'to change clothes / relocate', 'verben', null, '-'],
  ['kaufen', 'to buy / purchase', 'verben', null, '-'],
  ['einkaufen', 'to shop / go shopping', 'verben', null, '-'],
  ['verkaufen', 'to sell', 'verben', null, '-'],
  ['bezahlen / zahlen', 'to pay', 'verben', null, '-'],
  ['kosten', 'to cost', 'verben', null, '-'],
  ['bestellen', 'to order (goods/food)', 'verben', null, '-'],
  ['nehmen', 'to take', 'verben', null, '-'],
  ['geben', 'to give', 'verben', null, '-'],
  ['bringen', 'to bring / take to', 'verben', null, '-'],
  ['mitbringen', 'to bring along', 'verben', null, '-'],
  ['mitkommen', 'to come along', 'verben', null, '-'],
  ['mitnehmen', 'to take along', 'verben', null, '-'],
  ['abholen', 'to pick up / collect', 'verben', null, '-'],
  ['anrufen', 'to call by phone', 'verben', null, '-'],
  ['telefonieren', 'to talk on phone', 'verben', null, '-'],
  ['öffnen / aufmachen', 'to open', 'verben', null, '-'],
  ['schließen / zumachen', 'to close / shut', 'verben', null, '-'],
  ['anmachen / einschalten', 'to switch on (light/device)', 'verben', null, '-'],
  ['ausmachen / ausschalten', 'to switch off (light/device)', 'verben', null, '-'],
  ['drücken', 'to press / push', 'verben', null, '-'],
  ['ziehen', 'to pull', 'verben', null, '-'],
  ['suchen', 'to search / look for', 'verben', null, '-'],
  ['finden', 'to find / consider', 'verben', null, '-'],
  ['verlieren', 'to lose', 'verben', null, '-'],
  ['brauchen', 'to need / require', 'verben', null, '-'],
  ['helfen', 'to help / assist', 'verben', null, '-'],
  ['danken', 'to thank', 'verben', null, '-'],
  ['bitten', 'to ask / request', 'verben', null, '-'],
  ['gefallen', 'to please / appeal to', 'verben', null, '-'],
  ['gehören', 'to belong to', 'verben', null, '-'],
  ['passen', 'to fit / suit', 'verben', null, '-'],
  ['stimmen', 'to be right / correct', 'verben', null, '-'],
  ['besuchen', 'to visit', 'verben', null, '-'],
  ['treffen', 'to meet', 'verben', null, '-'],
  ['einladen', 'to invite', 'verben', null, '-'],
  ['feiern', 'to celebrate', 'verben', null, '-'],
  ['gratulieren', 'to congratulate', 'verben', null, '-'],
  ['schenken', 'to give as present', 'verben', null, '-'],
  ['spielen', 'to play', 'verben', null, '-'],
  ['singen', 'to sing', 'verben', null, '-'],
  ['tanzen', 'to dance', 'verben', null, '-'],
  ['lachen', 'to laugh', 'verben', null, '-'],
  ['weinen', 'to cry / weep', 'verben', null, '-'],
  ['warten', 'to wait', 'verben', null, '-'],
  ['erwarten', 'to expect', 'verben', null, '-'],
  ['beginnen / anfangen', 'to begin / start', 'verben', null, '-'],
  ['enden / aufhören', 'to end / stop', 'verben', null, '-'],
  ['dauern', 'to last / take time', 'verben', null, '-'],
  ['rauchen', 'to smoke', 'verben', null, '-'],
  ['funktionieren', 'to work / function', 'verben', null, '-'],
  ['reparieren', 'to repair / fix', 'verben', null, '-'],
  ['wechseln', 'to change / exchange', 'verben', null, '-'],
  ['umtauschen', 'to exchange (store goods)', 'verben', null, '-'],
  ['ausfüllen', 'to fill in / out (form)', 'verben', null, '-'],
  ['unterschreiben', 'to sign (document)', 'verben', null, '-'],
  ['buchen', 'to book / reserve', 'verben', null, '-'],
  ['reservieren', 'to reserve', 'verben', null, '-'],
  ['übernachten', 'to spend the night', 'verben', null, '-'],
  ['abfahren', 'to depart (vehicle)', 'verben', null, '-'],
  ['ankommen', 'to arrive', 'verben', null, '-'],
  ['einsteigen', 'to board / get on', 'verben', null, '-'],
  ['aussteigen', 'to disembark / get off', 'verben', null, '-'],
  ['umsteigen', 'to transfer / change trains', 'verben', null, '-'],
  ['halten', 'to stop / hold', 'verben', null, '-'],
  ['verpassen', 'to miss (train/bus)', 'verben', null, '-'],
  ['abfliegen', 'to take off (flight)', 'verben', null, '-'],
  ['landen', 'to land (plane)', 'verben', null, '-'],
  ['wehtun', 'to hurt / ache', 'verben', null, '-'],
  ['fehlen', 'to be missing / lack', 'verben', null, '-']
];

// Map the raw tuples directly into the engine's standard object format
window.DM_VOCAB = rawA1Vocab.map(([de, en, cat, gender, plural]) => ({
  de,
  en,
  cat,
  gender,
  article: gender,
  plural: plural === '-' ? null : plural
}));